---
openapi: 3.0.0
info:
  title: Clothing Suggestion Website API
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/ADITHYAKRISHNAKUMAR/ClothingApplication/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://{domain}/{basePath}
  description: Production server
paths:
  /login:
    post:
      summary: Authenticate user and generate session token
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login_body'
      responses:
        "200":
          description: User authenticated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "401":
          description: Invalid credentials provided
  /logout:
    post:
      summary: End user session and invalidate session token
      operationId: logoutUser
      parameters:
      - name: session_token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: User session ended successfully
        "401":
          description: Invalid session token provided
  /history:
    get:
      summary: Retrieve user's search history
      operationId: getUserHistory
      parameters:
      - name: session_token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: User search history retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_1'
  /upload:
    post:
      summary: Upload user's image to S3 bucket
      operationId: uploadImage
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/upload_body'
      responses:
        "200":
          description: Image uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
  /process:
    post:
      summary: Trigger image processing and product suggestion
      operationId: processImage
      parameters:
      - name: session_token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/process_body'
      responses:
        "200":
          description: Image processed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
  /recognize:
    post:
      summary: Identify item in the uploaded image using AI/ML
      operationId: recognizeProduct
      parameters:
      - name: session_token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/recognize_body'
        required: true
      responses:
        "200":
          description: Product recognized successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        "400":
          description: Invalid request body
  /suggest:
    get:
      summary: Get personalized product recommendations for the user
      operationId: getUserRecommendations
      parameters:
      - name: session_token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: category
        in: query
        description: Filter recommendations by category
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: User recommendations retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_5'
  /product/{product_id}:
    get:
      summary: Get product details by product ID
      operationId: getProductDetails
      parameters:
      - name: product_id
        in: path
        description: Unique identifier for the product
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Product details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
  /products:
    get:
      summary: Get list of products
      operationId: getProducts
      parameters:
      - name: category
        in: query
        description: Filter products by category
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Products retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_7'
  /coupons:
    get:
      summary: Retrieves a list of coupons for a dress
      parameters:
      - name: dress_id
        in: query
        description: The ID of the dress to retrieve coupons for
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_8'
        "400":
          description: Invalid request
        "404":
          description: Dress not found
  /favorites:
    get:
      summary: Get user's favorite products
      operationId: getUserFavorites
      parameters:
      - name: session_token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: User's favorite products retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200_9'
    post:
      summary: Add product to user's favorite list
      operationId: addFavoriteProduct
      parameters:
      - name: session_token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/favorites_body'
      responses:
        "201":
          description: Product added to user's favorites successfully
        "400":
          description: Invalid request body
    delete:
      summary: Remove product from user's favorite list
      operationId: removeFavoriteProduct
      parameters:
      - name: session_token
        in: header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: product_name
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          description: Name of the product to remove from favorites
      responses:
        "200":
          description: Product removed from user's favorites successfully
        "404":
          description: Product not found in user's favorites
components:
  schemas:
    login_body:
      required:
      - password
      - username
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    inline_response_200:
      type: object
      properties:
        token:
          type: string
    inline_response_200_1:
      type: object
      properties:
        search_date:
          type: string
          format: date-time
        search_query:
          type: string
    upload_body:
      required:
      - file
      type: object
      properties:
        file:
          type: string
          format: binary
    inline_response_200_2:
      type: object
      properties:
        image_url:
          type: string
          description: URL of the uploaded image in S3 bucket
    process_body:
      required:
      - image_url
      type: object
      properties:
        image_url:
          type: string
          description: URL of the uploaded image in S3 bucket
    inline_response_200_3:
      type: object
      properties:
        suggested_products:
          type: array
          items:
            type: object
            properties:
              product_name:
                type: string
              product_url:
                type: string
              product_image_url:
                type: string
        coupon_code:
          type: string
          description: Applicable coupon/discount code (optional)
    recognize_body:
      type: object
      properties:
        image:
          type: string
          description: The image to be analyzed
          format: binary
    inline_response_200_4:
      type: object
      properties:
        product_name:
          type: string
          description: The name of the recognized product
        confidence:
          type: number
          description: The confidence score of the recognition (between 0 and 1)
          format: float
    inline_response_200_5:
      type: object
      properties:
        product_name:
          type: string
        product_url:
          type: string
        product_image_url:
          type: string
    inline_response_200_6:
      type: object
      properties:
        product_name:
          type: string
        product_description:
          type: string
        product_price:
          type: number
        product_image_url:
          type: string
        product_category:
          type: string
    inline_response_200_7:
      type: object
      properties:
        product_name:
          type: string
        product_url:
          type: string
        product_image_url:
          type: string
        product_price:
          type: number
        product_category:
          type: string
    inline_response_200_8:
      type: object
      properties:
        coupons:
          type: array
          items:
            type: object
            properties:
              coupon_id:
                type: integer
              coupon_code:
                type: string
              discount:
                type: number
              expiration_date:
                type: string
                format: date-time
    inline_response_200_9:
      type: object
      properties:
        product_name:
          type: string
        product_url:
          type: string
        product_image_url:
          type: string
        product_category:
          type: string
          enum:
          - tops
          - bottoms
          - shoes
          - accessories
        product_price:
          type: number
          format: float
        product_description:
          type: string
    favorites_body:
      required:
      - product_category
      - product_description
      - product_image_url
      - product_name
      - product_price
      - product_url
      type: object
      properties:
        product_name:
          type: string
          description: Name of the product
          example: Nike Air Max 90
        product_url:
          type: string
          description: URL of the product page
          example: https://www.nike.com/air-max-90
        product_image_url:
          type: string
          description: URL of the product image
          example: https://www.nike.com/air-max-90.jpg
        product_category:
          type: string
          description: Category of the product
          example: shoes
          enum:
          - tops
          - bottoms
          - shoes
          - accessories
        product_price:
          type: number
          description: Price of the product
          format: float
          example: 129.99
        product_description:
          type: string
          description: Description of the product
          example: The Nike Air Max 90 is a timeless classic, featuring the iconic Air-Sole unit and premium leather and synthetic leather materials.
